stages:
  - deploy

production:
  stage: deploy
  image: lorisleiva/laravel-docker:latest
  variables:
    HEROKU_API_KEY: $HEROKU_PRODUCTION_API_KEY
  script:
    - apk add ruby ruby-dev ruby-irb ruby-rake ruby-io-console ruby-bigdecimal ruby-json ruby-bundler yarn ruby-rdoc >> /dev/null
    - apk update
    - gem install dpl >> /dev/null
    - dpl --provider=heroku --app=liberyen --api-key=$HEROKU_API_KEY
